apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: dotnet-basic-mrmokkcw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/dotnet-basic-mrmokkcw:e9e887cdbe5ec32d4d003480946f52abd60471e4@sha256:0e29c324f94ae9c8bf6dde2658a4adcfa28e153c6f0ba8df2cc0a2e8f8349582
        name: container-image  
